"""Add url field to event

Revision ID: 1b092c46116e
Revises: f2ff5a1ba423
Create Date: 2020-12-31 18:37:22.409605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b092c46116e'
down_revision = 'f2ff5a1ba423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'url')
    # ### end Alembic commands ###
